### ISSUE TITLE
wrapping problem

### ISSUE THREAD

**Issue by evleur** [bmbrands/theme_cerulean#3]
The theme has a wrapping problem. I've implemented the one topic format which works fine with different themes. The bootstrap theme gives a problem as well as the Cerulean theme which works with the bootstrap theme.

I would like to start using the themes with the one topic format begin september so help would be usefull.

![schermafbeelding 2014-08-26 om 15 42 52](https://cloud.githubusercontent.com/assets/8565693/4056401/1b8295a4-2dba-11e4-908d-d59fef888b9d.png)

**Comment by bmbrands** [comment]
not a cerulean issue. See https://github.com/bmbrands/theme_bootstrap/issues/332 for the correct issue location
